let body = JSON.parse($response.body);

body['data']['entities'] = [
      "entities" : [
        {
          "banner" : "",
          "content" : "",
          "dateline" : 1545629009,
          "description" : "",
          "entities" : [
            {
              "entityId" : "",
              "entityType" : "groupTitle",
              "page_name" : null,
              "pic" : "",
              "title" : "关注分组",
              "url" : ""
            },
            {
              "entityId" : "",
              "entityType" : "page",
              "page_name" : "",
              "pic" : "",
              "title" : "全部关注",
              "url" : "/page?url=V9_HOME_TAB_FOLLOW"
            },
            {
              "entityId" : "",
              "entityType" : "page",
              "page_name" : "",
              "pic" : "",
              "title" : "好友关注",
              "url" : "/page?url=V9_HOME_TAB_FOLLOW&type=circle"
            },
            {
              "entityId" : "",
              "entityType" : "page",
              "page_name" : "",
              "pic" : "",
              "title" : "话题关注",
              "url" : "/page?url=V9_HOME_TAB_FOLLOW&type=topic"
            },
            {
              "entityId" : "",
              "entityType" : "page",
              "page_name" : "",
              "pic" : "",
              "title" : "数码关注",
              "url" : "/page?url=V9_HOME_TAB_FOLLOW&type=product"
            },
            {
              "entityId" : "",
              "entityType" : "page",
              "page_name" : "",
              "pic" : "",
              "title" : "应用关注",
              "url" : "/page?url=V9_HOME_TAB_FOLLOW&type=apk"
            }
          ],
          "entityId" : 412,
          "entityType" : "page",
          "extraData" : "{\"saveSubTabSelectedState\":\"1\"}",
          "hitnum" : 550157313,
          "id" : 412,
          "is_head_card" : 0,
          "lastupdate" : 1647489082,
          "logo" : "http://image.coolapk.com/image/2019/0326/14/1553580240_0612-0-o_1d6s9iank1i278k41ef81ibg10k3i-uid-611629@96x96.png",
          "order" : 1,
          "page_extras" : "",
          "page_fixed" : 1,
          "page_name" : "V9_HOME_TAB_FOLLOW",
          "page_type" : 9,
          "page_visibility" : 1,
          "platform" : 0,
          "status" : 1,
          "title" : "关注",
          "uid" : 10002,
          "url" : "/page?url=V9_HOME_TAB_FOLLOW",
          "username" : "阿酷"
        },
        {
          "banner" : "",
          "content" : "",
          "dateline" : 1545639814,
          "description" : "",
          "entities" : [

          ],
          "entityId" : 420,
          "entityType" : "page",
          "extraData" : "",
          "hitnum" : 0,
          "id" : 420,
          "is_head_card" : 0,
          "lastupdate" : 1557288241,
          "logo" : "http://image.coolapk.com/image/2019/0326/13/1553579990_7328-0-o_1d6s9an1s1klakgc61smi7jvgi-uid-611629@96x96.png",
          "order" : 2,
          "page_extras" : "",
          "page_fixed" : 1,
          "page_name" : "V9_HOME_TAB_HEADLINE",
          "page_type" : 9,
          "page_visibility" : 1,
          "platform" : 0,
          "status" : 1,
          "title" : "头条",
          "uid" : 10002,
          "url" : "/main/headline",
          "username" : "阿酷"
        },
        {
          "banner" : "",
          "content" : "",
          "dateline" : 1545638658,
          "description" : "",
          "entities" : [

          ],
          "entityId" : 416,
          "entityType" : "page",
          "extraData" : "",
          "hitnum" : 96103402,
          "id" : 416,
          "is_head_card" : 0,
          "lastupdate" : 1615187196,
          "logo" : "http://image.coolapk.com/image/2019/0326/14/1553580309_0906-0-o_1d6s9ke3cd7c1tlfn3g1gmnci1i-uid-611629@96x96.png",
          "order" : 6,
          "page_extras" : "",
          "page_fixed" : 0,
          "page_name" : "V9_HOME_TAB_TOPIC",
          "page_type" : 9,
          "page_visibility" : 1,
          "platform" : 0,
          "status" : 1,
          "title" : "话题",
          "uid" : 10002,
          "url" : "/page?url=V9_HOME_TAB_TOPIC",
          "username" : "阿酷"
        },
        {
          "banner" : "",
          "content" : "",
          "dateline" : 1606992206,
          "description" : "",
          "entities" : [

          ],
          "entityId" : 1229,
          "entityType" : "page",
          "extraData" : "",
          "hitnum" : 29105286,
          "id" : 1229,
          "is_head_card" : 0,
          "lastupdate" : 1607591454,
          "logo" : "http://image.coolapk.com/image/2019/1106/13/1573019434_908-0-o_1dovk7fjkpjv12m111f31q6qi34a-uid-1603081@96x96.png",
          "order" : 4,
          "page_extras" : "",
          "page_fixed" : 0,
          "page_name" : "V11_HOME_TAB_NEWS",
          "page_type" : 9,
          "page_visibility" : 1,
          "platform" : 0,
          "status" : 1,
          "title" : "快讯",
          "uid" : 1603081,
          "url" : "/page?url=V11_HOME_TAB_NEWS",
          "username" : "匿名游客"
        },
        {
          "banner" : "",
          "content" : "",
          "dateline" : 1545639705,
          "description" : "",
          "entities" : [

          ],
          "entityId" : 419,
          "entityType" : "page",
          "extraData" : "",
          "hitnum" : 54222640,
          "id" : 419,
          "is_head_card" : 0,
          "lastupdate" : 1635490759,
          "logo" : "http://image.coolapk.com/image/2019/0326/14/1553580336_1119-0-o_1d6s9l8ifvav15n91ho1upcf9i-uid-611629@96x96.png",
          "order" : 9,
          "page_extras" : "",
          "page_fixed" : 0,
          "page_name" : "V9_HOME_TAB_COOLPIC",
          "page_type" : 9,
          "page_visibility" : 1,
          "platform" : 0,
          "status" : 1,
          "title" : "酷图",
          "uid" : 10002,
          "url" : "/page?url=V9_HOME_TAB_COOLPIC",
          "username" : "阿酷"
        },
        {
          "banner" : "",
          "content" : "",
          "dateline" : 1639730225,
          "description" : "",
          "entities" : [

          ],
          "entityId" : 1742,
          "entityType" : "page",
          "extraData" : "",
          "hitnum" : 2721741,
          "id" : 1742,
          "is_head_card" : 0,
          "lastupdate" : 1640144831,
          "logo" : "http://image.coolapk.com/image/2021/1222/11/1640143649_8953-0-o_1fng2rtur1a9k15u590s1dkk1vqui-uid-12202@96x96.png",
          "order" : 7,
          "page_extras" : "",
          "page_fixed" : 0,
          "page_name" : "V11_HOME_NEW",
          "page_type" : 9,
          "page_visibility" : 1,
          "platform" : 0,
          "status" : 1,
          "title" : "新机",
          "uid" : 12202,
          "url" : "/page?url=V11_HOME_NEW",
          "username" : "酷安小编"
        },
        {
          "banner" : "",
          "content" : "",
          "dateline" : 1635490837,
          "description" : "",
          "entities" : [

          ],
          "entityId" : 1681,
          "entityType" : "page",
          "extraData" : "",
          "hitnum" : 1986594,
          "id" : 1681,
          "is_head_card" : 0,
          "lastupdate" : 1640144836,
          "logo" : "http://image.coolapk.com/image/2021/1029/16/20211029-162207-0-o_1fj5i8tnh1g517kfijs1f4k1um3i-uid-12202@96x96.png",
          "order" : 8,
          "page_extras" : "",
          "page_fixed" : 0,
          "page_name" : "V11_HOME_TAB_JC",
          "page_type" : 9,
          "page_visibility" : 1,
          "platform" : 0,
          "status" : 1,
          "title" : "教程",
          "uid" : 12202,
          "url" : "/page?url=V11_HOME_TAB_JC",
          "username" : "酷安小编"
        },
        {
          "banner" : "",
          "content" : "",
          "dateline" : 1545637322,
          "description" : "",
          "entities" : [

          ],
          "entityId" : 415,
          "entityType" : "page",
          "extraData" : "",
          "hitnum" : 275042817,
          "id" : 415,
          "is_head_card" : 0,
          "lastupdate" : 1575969840,
          "logo" : "http://image.coolapk.com/image/2019/0326/14/1553580287_7679-0-o_1d6s9jpfg98d1jnn19mm1rfv1bik1u-uid-611629@96x96.png",
          "order" : 3,
          "page_extras" : "",
          "page_fixed" : 0,
          "page_name" : "V9_HOME_TAB_RANKING",
          "page_type" : 9,
          "page_visibility" : 0,
          "platform" : 0,
          "status" : 1,
          "title" : "热榜",
          "uid" : 10002,
          "url" : "/page?url=V9_HOME_TAB_RANKING",
          "username" : "阿酷"
        },
        {
          "banner" : "",
          "content" : "",
          "dateline" : 1545639234,
          "description" : "",
          "entities" : [

          ],
          "entityId" : 417,
          "entityType" : "page",
          "extraData" : "",
          "hitnum" : 16732930,
          "id" : 417,
          "is_head_card" : 0,
          "lastupdate" : 1599009328,
          "logo" : "http://image.coolapk.com/image/2019/0326/14/1553580374_3749-0-o_1d6s9mdrcipjuchvlf1qvc12mli-uid-611629@96x96.png",
          "order" : 15,
          "page_extras" : "",
          "page_fixed" : 0,
          "page_name" : "V9_HOME_TAB_WENDA",
          "page_type" : 9,
          "page_visibility" : 0,
          "platform" : 0,
          "status" : 1,
          "title" : "问答",
          "uid" : 10002,
          "url" : "/page?url=V9_HOME_TAB_WENDA",
          "username" : "阿酷"
        }
      ],
$done({body: JSON.stringify(body)});
